### PR TITLE
Optimize broadcasting on the pdf function

### LINKED ISSUE #47: Unexpected behavior of `pdf` function
There was a subtle bug that slipped throught the recent PR. 
Now `pdf` broadcasting (i.e pdf.(u,v)) with u and v being the same shape doesn't throw required error. 

```julia
julia> using CategoricalDistributions

julia> using CategoricalDistributions.CategoricalArrays

julia> import CategoricalDistributions: classes

julia> import Random

julia> n = 10
10

julia> P = rand(rng, n);

julia> all_classes = categorical(["no", "yes"], ordered=true)
2-element CategoricalArray{String,1,UInt32}:
 "no"
 "yes"

julia> u = UnivariateFinite(all_classes, P, augment=true)
10-element UnivariateFiniteVector{OrderedFactor{2}, String, UInt32, Float64}:
 UnivariateFinite{OrderedFactor{2}}(no=>0.791, yes=>0.209)
 UnivariateFinite{OrderedFactor{2}}(no=>0.198, yes=>0.802)
 UnivariateFinite{OrderedFactor{2}}(no=>0.617, yes=>0.383)
 UnivariateFinite{OrderedFactor{2}}(no=>0.838, yes=>0.162)
 UnivariateFinite{OrderedFactor{2}}(no=>0.688, yes=>0.312)
 UnivariateFinite{OrderedFactor{2}}(no=>0.456, yes=>0.544)
 UnivariateFinite{OrderedFactor{2}}(no=>0.12, yes=>0.88)
 UnivariateFinite{OrderedFactor{2}}(no=>0.498, yes=>0.502)
 UnivariateFinite{OrderedFactor{2}}(no=>0.973, yes=>0.0275)
 UnivariateFinite{OrderedFactor{2}}(no=>0.813, yes=>0.187)

julia> v0 = categorical(rand(rng, string.(classes(u)), n))
10-element CategoricalArray{String,1,UInt32}:
 "yes"
 "yes"
 "yes"
 "no"
 "no"
 "yes"
 "no"
 "no"
 "no"
 "yes"

julia> v1 = categorical([v0[1:end-1];"strange_level"])
10-element CategoricalArray{String,1,UInt32}:
 "yes"
 "yes"
 "yes"
 "no"
 "no"
 "yes"
 "no"
 "no"
 "no"
 "strange_level"

julia> broadcast(pdf, u, v1) # expected a domain error as "strange_level" isn't in `classes(u)`
10-element Vector{Float64}:
 0.20925433092734314
 0.8018950788093753
 0.38303140778222167
 0.8375766533857434
 0.6876763032452158
 0.5438284429874609
 0.12032258846543775
 0.49776351230903493
 0.9725006313210285
 0.0
```

@bkamins @ablaom

### PR DESCRIPTION
**Pull request by OkonSamuel**
This PR continues from where #40 left off. It replaces `findfirst(==(x), classes(u))` with the faster 
`get(CategoricalArrays.pool(classes(u)), x)` which also handles type promotion of `x` internally.

The existing code was further cleaned up and more tests were added.
closes #47 

cc. @bkamins @ablaom

### CODE REVIEW

**Review by ablaom — APPROVED** [review]
Thanks for this, @OkonSamuel.

Looks good to me.

@bkamins Do you want to comment?

**Review by bkamins — APPROVED** [review]
Looks good. Maybe it would be worth to add similar tests when `missing` values are present?

**Comment by OkonSamuel** [comment]
> Looks good. Maybe it would be worth to add similar tests when `missing` values are present?

Yes, those tests already exist. https://github.com/JuliaAI/CategoricalDistributions.jl/pull/48/files#diff-e7ba25de6eb72839907438ab2ca39a49fdd7025e031c7b6c95ad1a6842e1e613R161

**Comment by bkamins** [comment]
But if they exist then why they have not caught the error in implementation previously?
I meant similar test as https://github.com/JuliaAI/CategoricalDistributions.jl/pull/48/files#diff-e7ba25de6eb72839907438ab2ca39a49fdd7025e031c7b6c95ad1a6842e1e613R174 but with `vm` (this is minor).

**Pull request merged**
